version: '3.8'
services:
  piword:
    build: .
    container_name: piword
    ports:
      - "4567:4567"
    environment:
      - NODE_ENV=production
  api_letra:
    build:
      context: .
      dockerfile: api_letra/Dockerfile
    container_name: api_letra
    ports:
      - "1333:1333"
    environment:
      - NODE_ENV=production